LIBMAKE+=../libraries/ad799x/Makefile
CPPSRC+=../libraries/ad799x/ad799x.cpp
include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/packet/Makefile
EXTRAINCDIRS+=../libraries/ad799x/


