LIBMAKE+=../libraries/FileCircular/Makefile
CPPSRC+=../libraries/FileCircular/FileCircular.cpp
EXTRAINCDIRS +=../libraries/FileCircular/

include ../libraries/Circular/Makefile
#include the correct Makefile for the file library (Riegel or Kwan)
#before including this Makefile
#include ../libraries/fat/Makefile


