LIBMAKE+=../libraries/bmp180/Makefile
CPPSRC+=../libraries/bmp180/bmp180.cpp
include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/packet/Makefile
EXTRAINCDIRS+=../libraries/bmp180/


