CPPSRC+=../libraries/fat/cluster.cpp
CPPSRC+=../libraries/fat/direntry.cpp
CPPSRC+=../libraries/fat/file.cpp
LIBMAKE+=../libraries/fat/Makefile
EXTRAINCDIRS+=../libraries/fat/

include ../libraries/Partition/Makefile

