LIBMAKE+=../libraries/Wire/StateTwoWire/Makefile
CPPSRC+=../libraries/Wire/StateTwoWire/StateTwoWire.cpp
include ../libraries/gpio/Makefile
include ../libraries/Wire/Makefile
EXTRAINCDIRS+=../libraries/Wire/StateTwoWire/
